### ISSUE TITLE
Implement JSON Data Structure for app data

### ISSUE THREAD

**Issue by thebongy** [thebongy/Vote#1]
We need to create a data structure based on features that will be implemented, and required data for the same. We need not even use JSON, if something better comes up

**Comment by stormalinblue** [comment]
Predictably, there are multiple types of independent communications that will take place between any pair of server and client. You seem to suggest a blanket structure.

**Comment by thebongy** [comment]
A blanket structure?

**Comment by thebongy** [comment]
I think in terms of server side, we surely need to use sockets this time. And we can do token authentication on the security side, requiring each vote to be signed with the token given to the polling booth

**Comment by thebongy** [comment]
Closing issue backlog, discussion can continue here if required.
